name: bloodinsight
description: "A smart bloodwork monitoring app that helps users track, analyze,
  and gain insights into their health data."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  cloud_firestore: ^5.6.3
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_google_maps_webservices: ^1.1.1
  flutter_local_notifications: ^18.0.1
  flutter_native_splash: ^2.4.4
  flutter_timezone: ^4.1.0
  freezed: 3.0.0-0.0.dev
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  geolocator: ^13.0.2
  get_it: ^8.0.3
  go_router: ^14.8.0
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.6
  google_maps_flutter: ^2.10.0
  google_sign_in: ^6.2.2
  grouped_list: ^6.0.0
  intl: ^0.20.2
  lottie: ^3.3.1
  provider: ^6.1.2
  rxdart: ^0.28.0
  shared_preferences: ^2.5.1
  smooth_page_indicator: ^1.2.0+3
  stream_transform: ^2.1.1
  timezone: ^0.10.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.6
  flutter_env_native: ^0.1.0
  flutter_test:
    sdk: flutter
  leancode_lint: ^14.2.0
  mocktail: ^1.0.4

flutter_native_splash:
  color: "#f0ff5d"
  image: assets/splashscreen/splash.png
  branding: "assets/splashscreen/splash_brand.png"
  branding_bottom_padding: 36
  android_12:
    color: "#f0ff5d"
    image: assets/splashscreen/android12splash.png
    branding: assets/splashscreen/splash_brand.png
  ios: false

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/animations/
