// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUp0NFTKpzUUdmpf88Swgl0NlKVmr5Roo',
    appId: '1:298361829564:web:064b58905c86967cfbf8b9',
    messagingSenderId: '298361829564',
    projectId: 'bloodinsight-f1r3d3v',
    authDomain: 'bloodinsight-f1r3d3v.firebaseapp.com',
    storageBucket: 'bloodinsight-f1r3d3v.firebasestorage.app',
    measurementId: 'G-PSH6P7RX3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKlHUUTubY5zFOD26rIPALDm5cG1j7ejM',
    appId: '1:298361829564:android:b39007a2b3e166d8fbf8b9',
    messagingSenderId: '298361829564',
    projectId: 'bloodinsight-f1r3d3v',
    storageBucket: 'bloodinsight-f1r3d3v.firebasestorage.app',
  );
}
