name: Setup environment
description: Setup environment for Flutter project

inputs:
  GOOGLE_MAPS_API:
    description: 'Google Maps API key'
    required: true
  GEMINI_API:
    description: 'Gemini API key'
    required: true

runs:
  using: composite
  steps:
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
        cache: gradle

    - name: Setup Android cmdline tools
      uses: android-actions/setup-android@v3
      with:
        log-accepted-android-sdk-licenses: false

    - name: Setup Android SDK
      uses: maxim-lobanov/setup-android-tools@v1
      with:
        packages: |
          platforms;android-31
          ndk;27.0.12077973
        cache: true

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.27.4
        channel: "stable"
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
        cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
        architecture: x64

    - name: Install dependencies
      run: flutter pub get
      shell: bash

    - name: Create .env file
      env:
        GOOGLE_MAPS_API: ${{ inputs.GOOGLE_MAPS_API }}
        GEMINI_API: ${{ inputs.GEMINI_API }}
      run: |
        touch .env
        echo "GOOGLE_MAPS_API=$GOOGLE_MAPS_API" >> .env
        echo "GEMINI_API=$GEMINI_API" >> .env
      shell: bash
