name: Setup environment
description: Setup environment for Flutter project

inputs:
  GOOGLE_MAPS_API:
    description: 'Google Maps API key'
    required: true
  GEMINI_API:
    description: 'Gemini API key'
    required: true

runs:
  using: composite
  steps:
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: "zulu"
        java-version: "21.x"
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: "stable"
        flutter-version: 3.27.4

    - name: Cache pub dependencies
      id: cache-pub-deps
      uses: actions/cache@v4
      with:
        path: |
          ~/.pub-cache
          .dart_tool
        key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-pub-

    - name: Install dependencies
      run: flutter pub get
      shell: bash

    - name: Create .env file
      env:
        GOOGLE_MAPS_API: ${{ inputs.GOOGLE_MAPS_API }}
        GEMINI_API: ${{ inputs.GEMINI_API }}
      run: |
        touch .env
        echo "GOOGLE_MAPS_API=$GOOGLE_MAPS_API" >> .env
        echo "GEMINI_API=$GEMINI_API" >> .env
      shell: bash
