name: CI
description: Continuous Integration for BloodInsight

on: [push, pull_request]

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/env_setup

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze --fatal-warnings

      - name: Run tests
        run: flutter test --dart-define-from-file=.env

  flutter_build_android:
    name: Build Android
    needs: flutter_test
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/env_setup

      - name: Build Android APK
        run: flutter build apk --dart-define-from-file=.env

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BloodInsight-Apk
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error

      - name: Build Android App Bundle
        run: flutter build appbundle --dart-define-from-file=.env

      - name: Upload Bundle Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BloodInsight-AppBundle
          path: build/app/outputs/bundle/release/app-release.aab
          if-no-files-found: error
